### PR TITLE
Set up PWA

### PR DESCRIPTION
**Pull request by LostCrew**

### CODE REVIEW

**Comment by jasongwartz** [comment]
Just did the Add to Home Screen - so cool! The icon is the VueJS logo, I’m assuming we can customize it in some way?

**Comment by LostCrew** [comment]
Agreed. Yes, they do, however there are online generators that create the various versions starting from your hi-res image 👍

**Comment by LostCrew** [comment]
We could stall this PR until we figure out a temporary logo 👍

**Comment by LostCrew** [comment]
Actually, I'll merge as-is and change the logo later

**Pull request merged**
